# Generated by Django 3.2.9 on 2021-11-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TirePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tire_positions',
            },
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_cars',
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField()),
                ('aspect_ratio', models.PositiveSmallIntegerField()),
                ('wheel_size', models.PositiveSmallIntegerField()),
                ('tire_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.tireposition')),
            ],
            options={
                'db_table': 'tires',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='front_tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_tire', to='cars.tire'),
        ),
        migrations.AddField(
            model_name='car',
            name='rear_tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rear_tire', to='cars.tire'),
        ),
    ]
