# Generated by Django 3.2.9 on 2021-11-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TirePosition',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='tire',
            old_name='tire_position',
            new_name='position',
        ),
    ]
