# Generated by Django 3.2.9 on 2021-11-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211126_1850'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='position',
            table='positions',
        ),
    ]
