# Generated by Django 3.2.9 on 2021-11-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_position_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
